name: Build Android APK (InventarioPro)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get Date
      id: get-date
      run: echo "date=$(date -u '+%Y%m%d')" >> $GITHUB_OUTPUT

    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: .buildozer_global
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}

    - name: Cache Buildozer directory
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer android debug
        buildozer_version: master

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: inventariopro-debug-apk-${{ github.run_number }}
        path: bin/*.apk
        retention-days: 30

    - name: Upload build logs (if failure)
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs-${{ github.run_number }}
        path: |
          .buildozer/android/platform/python-for-android/dist/*/build.log
          .buildozer/android/platform/build-*/**/*.log
        retention-days: 7